### ISSUE TITLE
Internal error: Dictionary is full!

### ISSUE THREAD

**Issue by jangorecki** [tidyverse/dplyr#5291]
Getting an internal error when trying to run groupby query on biggish data.
1e9 rows, csv size 48 GB.
dplyr 1.0.0. R 3.6.3. Ubuntu 16.04.
```r
ans <- x %>% group_by(id1, .drop=TRUE) %>% summarise(v1=sum(v1))
#Error: Internal error: Dictionary is full!
```
preview of data (note that I loaded with `head -100 data.csv`, the original file that cause the problem has 1e9 rows).
```r
x
# A tibble: 99 x 9
#   id1   id2   id3            id4   id5     id6    v1    v2    v3
#   <fct> <fct> <fct>        <int> <int>   <int> <int> <int> <dbl>
# 1 id046 id011 id0002718685    44     5 1315045     3     2 44.0 
# 2 id041 id014 id0006632358    46    61 7468642     4     3 35.3 
# 3 id036 id043 id0005896759    64    50 6211511     5     4 39.2 
```
Cardinalities of `id` columns
```
1e2, 1e2, 1e7, 1e2, 1e2, 1e7
```
Generate data
```sh
wget https://raw.githubusercontent.com/h2oai/db-benchmark/5bc22510f77241790e9c03c2c636836e2089e960/_data/groupby-datagen.R
Rscript groupby-datagen.R 1e9 1e2 0 0
```

**Comment by hadley** [comment]
Tracking in vctrs

**Comment by isaactpetersen** [comment]
I also have this issue. The following code:

```
theta_longByIDWaveRaterIter %>%
  group_by(tcid, wave, rater, construct) %>%
  summarize(theta = mean(latent, na.rm = TRUE),
            CI05 = quantile(latent,.05),
            CI95 = quantile(latent,.95))
```

yields the following error:

```
Error: Internal error in `dict_hash_with()`: Dictionary is full.
Backtrace:
     █
  1. └─`%>%`(...)
  2.   ├─base::withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
  3.   └─base::eval(quote(`_fseq`(`_lhs`)), env, env)
  4.     └─base::eval(quote(`_fseq`(`_lhs`)), env, env)
  5.       └─`_fseq`(`_lhs`)
  6.         └─magrittr::freduce(value, `_function_list`)
  7.           └─function_list[[i]](value)
  8.             ├─dplyr::group_by(., tcid, wave, rater, construct, iter)
  9.             └─dplyr:::group_by.data.frame(...)
 10.               └─dplyr::grouped_df(groups$data, groups$group_names, .drop)
 11.                 └─dplyr:::compute_groups(data, vars, drop = drop)
 12.                   └─dplyr:::vec_split_id_order(group_vars)
 13.                     └─vctrs::vec_group_loc(x)
 14.                       └─(function () ...
```

Here's my `sessionInfo()`:

```
R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /opt/ssoft/apps/2020.2/linux-centos7-x86_64/gcc-4.8.5/intel-mkl-2020.2.254-tdhfzki/compilers_and_libraries_2020.2.254/linux/mkl/lib/intel64_lin/libmkl_gf_lp64.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] data.table_1.13.2    rstan_2.21.2         StanHeaders_2.21.0-6
 [4] brms_2.14.4          Rcpp_1.0.5           forcats_0.5.0       
 [7] stringr_1.4.0        dplyr_1.0.2          purrr_0.3.4         
[10] readr_1.4.0          tidyr_1.1.2          tibble_3.0.4        
[13] ggplot2_3.3.2        tidyverse_1.3.0     

loaded via a namespace (and not attached):
  [1] TH.data_1.0-10       minqa_1.2.4          colorspace_2.0-0    
  [4] ellipsis_0.3.1       ggridges_0.5.2       rsconnect_0.8.16    
  [7] estimability_1.3     markdown_1.1         fs_1.5.0            
 [10] base64enc_0.1-3      rstudioapi_0.13      DT_0.16             
 [13] fansi_0.4.1          mvtnorm_1.1-1        lubridate_1.7.9.2   
 [16] xml2_1.3.2           bridgesampling_1.0-0 codetools_0.2-16    
 [19] splines_4.0.2        shinythemes_1.1.2    bayesplot_1.7.2     
 [22] projpred_2.0.2       jsonlite_1.7.1       nloptr_1.2.2.2      
 [25] packrat_0.5.0        broom_0.7.2          dbplyr_2.0.0        
 [28] shiny_1.5.0          httr_1.4.2           compiler_4.0.2      
 [31] emmeans_1.5.2-1      backports_1.2.0      assertthat_0.2.1    
 [34] Matrix_1.2-18        fastmap_1.0.1        cli_2.1.0           
 [37] later_1.1.0.1        htmltools_0.5.0      prettyunits_1.1.1   
 [40] tools_4.0.2          igraph_1.2.6         coda_0.19-4         
 [43] gtable_0.3.0         glue_1.4.2           reshape2_1.4.4      
 [46] V8_3.4.0             cellranger_1.1.0     vctrs_0.3.4         
 [49] nlme_3.1-150         crosstalk_1.1.0.1    ps_1.4.0            
 [52] rvest_0.3.6          lme4_1.1-25          mime_0.9            
 [55] miniUI_0.1.1.1       lifecycle_0.2.0      gtools_3.8.2        
 [58] statmod_1.4.35       MASS_7.3-53          zoo_1.8-8           
 [61] scales_1.1.1         colourpicker_1.1.0   hms_0.5.3           
 [64] promises_1.1.1       Brobdingnag_1.2-6    parallel_4.0.2      
 [67] sandwich_3.0-0       inline_0.3.16        shinystan_2.5.0     
 [70] gamm4_0.2-6          curl_4.3             gridExtra_2.3       
 [73] loo_2.3.1            stringi_1.5.3        dygraphs_1.1.1.6    
 [76] boot_1.3-25          pkgbuild_1.1.0       rlang_0.4.8         
 [79] pkgconfig_2.0.3      matrixStats_0.57.0   lattice_0.20-41     
 [82] rstantools_2.1.1     htmlwidgets_1.5.2    processx_3.4.4      
 [85] tidyselect_1.1.0     plyr_1.8.6           magrittr_1.5        
 [88] R6_2.5.0             generics_0.1.0       multcomp_1.4-15     
 [91] DBI_1.1.0            haven_2.3.1          pillar_1.4.6        
 [94] withr_2.3.0          mgcv_1.8-33          xts_0.12.1          
 [97] survival_3.2-7       abind_1.4-5          modelr_0.1.8        
[100] crayon_1.3.4         readxl_1.3.1         grid_4.0.2          
[103] callr_3.5.1          threejs_0.3.3        reprex_0.3.0        
[106] digest_0.6.27        xtable_1.8-4         httpuv_1.5.4        
[109] RcppParallel_5.0.2   stats4_4.0.2         munsell_0.5.0       
[112] shinyjs_2.0.0
```

**Comment by jangorecki** [comment]
@isaactpetersen It might not be the same issue despite raising same error message. The one you mentioned, reshaping, is likely to expand vector to a long vector. My example is a summary of 1e9 length vector, so there is technically no place for needing long vector here.

**Comment by fdq09eca** [comment]
what is the solution to the issue? I have the same problem.

**Comment by DavisVaughan** [comment]
You can try updating to the development version of vctrs. We have fixed this particular issue there

**Comment by ahdee** [comment]
Hi, using dplyr_1.0.8 any still having issues; can anyone confirm that the latest development version works? thanks.
