### ISSUE TITLE
Mutate error can persist until another successful mutate is run?

### ISSUE THREAD

**Issue by jtanman** [tidyverse/dplyr#5789]
I'm seeing errors for mutate persist across different datasets and code. Basically a code block that runs successfully, if run after getting a mutate error in my shiny app (and closing the app), will also begin to throw mutate errors. Then, if I happen to run a successful mutate that doesn't affect the original code block at all, the original code will then start to run successfully again.

Here is console output showing this. Unfortunately it's a little hard to replicate as the behavior of the code is changing each time!

```r
# CODE RUNS SUCCESSFULLY FIRST TIME
> df_error <- read_rds('df_error.rds')
> return_data <- df_error %>%
+   dplyr::mutate(
+     new_hour = paste0(hour, ':00'),
+     across(c(contains('notional'), buy_pool, net_buy_delta, -net_notional_percent_change), scales::label_dollar()),
+     across(c(contains('percent'), contains('concentration')), scales::label_percent(accuracy=.1))
+   )

# START SHINY APP AND GET ERROR
> shiny::runApp('position_limit_engine')
Loading required package: shiny

Attaching package: ‘shiny’

The following objects are masked from ‘package:DT’:

    dataTableOutput, renderDataTable


Attaching package: ‘plotly’

The following object is masked from ‘package:stats’:

    filter

The following object is masked from ‘package:graphics’:

    layout

The following object is masked from ‘package:ggplot2’:

    last_plot


Listening on http://127.0.0.1:7094
[1] 12
Warning in mean.default(hour) :
  argument is not numeric or logical: returning NA
Warning in mean.default(hour) :
  argument is not numeric or logical: returning NA
Warning: Error in : Problem with `mutate()` input `..2`.
x subscript out of bounds
ℹ Input `..2` is `(function (.cols = everything(), .fns = NULL, ..., .names = NULL) ...`.
  135: <Anonymous>

# SAME CODE NOW ALSO THROWS ERROR
> df_error <- read_rds('df_error.rds')
> return_data <- df_error %>%
+   dplyr::mutate(
+     new_hour = paste0(hour, ':00'),
+     across(c(contains('notional'), buy_pool, net_buy_delta, -net_notional_percent_change), scales::label_dollar()),
+     across(c(contains('percent'), contains('concentration')), scales::label_percent(accuracy=.1))
+   )
Error: Problem with `mutate()` input `..2`.
x subscript out of bounds
ℹ Input `..2` is `(function (.cols = everything(), .fns = NULL, ..., .names = NULL) ...`.
Run `rlang::last_error()` to see where the error occurred.

# RUN UNRELATED MUTATE THAT WORKS AND DOESN'T MODIFY ORIGINAL DATAFRAME
> df_error %>%
+   dplyr::mutate(
+     # hour = paste0(hour, ':00'),
+     across(c(contains('notional'), buy_pool, net_buy_delta, -net_notional_percent_change), scales::label_dollar()),
+     across(c(contains('percent'), contains('concentration')), scales::label_percent(accuracy=.1))
+   )
# A tibble: 3 x 21
  limit market period  hour num_stocks net_notional_pr… net_notional_new net_notional_de… net_notional_pe… concentration_p… concentration_n…
* <fct>  <dbl>  <dbl> <dbl>      <dbl> <chr>            <chr>            <chr>            <chr>            <chr>            <chr>           

    DATA

# … with 10 more variables: concentration_delta <chr>, concentration_buys_prev <chr>, concentration_buys_new <chr>,
#   concentration_buys_delta <chr>, affected_users <dbl>, affected_percentage_buyers <chr>, buy_pool <chr>, net_buy_percent_change <chr>,
#   net_buy_delta <chr>, net_buy_pool_percent_change <chr>

# CODE NOW RUNS SUCCESSFULLY AGAIN
> df_error <- read_rds('df_error.rds')
> return_data <- df_error %>%
+   dplyr::mutate(
+     new_hour = paste0(hour, ':00'),
+     across(c(contains('notional'), buy_pool, net_buy_delta, -net_notional_percent_change), scales::label_dollar()),
+     across(c(contains('percent'), contains('concentration')), scales::label_percent(accuracy=.1))
+   )
```

**Comment by hadley** [comment]
Could you please rework your reproducible example to use the [reprex package](http://reprex.tidyverse.org) ? That makes it easier to see both the input and the output, formatted in such a way that I can easily re-run in a local session.

**Comment by romainfrancois** [comment]
@jtanman Which version of `dplyr` was this. There was some issues we fixed in 1.0.5 (just released) so maybe it has been accidentally fixed. 

If you can't make it more reproducible, can you run your experiment again with dplyr 1.0.5 and let us know if this is fixed ?

**Comment by jtanman** [comment]
Unfortunately the error still exists with updated dplyr, but I can try to recreate a reproducible example using Shiny. Basically if I save the data frames that cause the error using browser() inside the Shiny app and reload them and run the same code that causes the Shiny error, the error no longer occurs. Once it occurs in the Shiny app, it will continue to occur outside the app until I run a successful unrelated mutate which then fixes everything.

**Comment by jtanman** [comment]
I was actually able to recreate it without the shiny app. Here's the reprex:

``` r
library(tidyverse)
library(scales)
#> 
#> Attaching package: 'scales'
#> The following object is masked from 'package:purrr':
#> 
#>     discard
#> The following object is masked from 'package:readr':
#> 
#>     col_factor

df_test <- tibble(group = c('a', 'a', 'b', 'b', 'b'), hour=parse_factor(as.character(c(1, 2, 1, 2, 1))), x = c(1,2,3, 4, 5), y=c(5, 6, 7, 8, 9))

summarise_df_input <- function(.data, func, group_vars) {
  df_agg <- .data %>%
    group_by(across(all_of(group_vars))) %>%
    summarise(across(everything(), func))
  
  return(df_agg)
}

df_grouped <- df_test %>% summarise_df_input(mean, 'group')
#> Warning in mean.default(hour): argument is not numeric or logical: returning NA

#> Warning in mean.default(hour): argument is not numeric or logical: returning NA

return_data <- df_test %>%
  dplyr::mutate(
    hour = paste(hour, ':00'),
    across(.cols = c(x, y), scales::label_dollar())
  )
#> Error: Problem with `mutate()` input `..2`.
#> x subscript out of bounds
#> ℹ Input `..2` is `(function (.cols = everything(), .fns = NULL, ..., .names = NULL) ...`.

return_data <- df_test %>%
  dplyr::mutate(
    across(.cols = c(x, y), scales::label_dollar())
  )

return_data <- df_test %>%
  dplyr::mutate(
    hour = paste(hour, ':00'),
    across(.cols = c(x, y), scales::label_dollar())
  )
```

<sup>Created on 2021-03-05 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by ahcyip** [comment]
I tried the code in this reprex and got the #> Error: Problem with `mutate()` input `..2`. in the reprex but not when running from the editor. Also, the error doesn't seem to re-appear the second and third time you try to do the mutate?

**Comment by jtanman** [comment]
Yes to clarify the mutate code that causes the error is performed 3x. Once successfully, then once with an error, and then lastly successfully again. The 2nd time you're referring to the code is actually changed a bit to not mutate on hour which causes it to run successfully, and then that somehow causes the 3rd time to run successfully once more.

**Comment by ahcyip** [comment]
@jtanman it will help if you clarify what dplyr version you used (you can change a reprex setting to get your sessioninfo)

**Comment by ahcyip** [comment]
OK I'm seeing it with dplyr 1.0.5 and I'm finding that it seems to work without error when running in editor BUT error shows up in reprex. 

``` r
library(tibble)
library(readr)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(scales)
#> 
#> Attaching package: 'scales'
#> The following object is masked from 'package:readr':
#> 
#>     col_factor

df_test <- tibble(group = c('a', 'a', 'b', 'b', 'b'), hour=parse_factor(as.character(c(1, 2, 1, 2, 1))), x = c(1,2,3, 4, 5), y=c(5, 6, 7, 8, 9))

return_data <- df_test %>%
  dplyr::mutate(
    hour = paste(hour, ':00'),
    across(.cols = c(x, y), scales::label_dollar())
  )

summarise_df_input <- function(.data, func, group_vars) {
  df_agg <- .data %>%
    group_by(across(all_of(group_vars))) %>%
    summarise(across(everything(), func))
  
  return(df_agg)
}

df_grouped <- df_test %>% summarise_df_input(mean, 'group')
#> Warning in mean.default(hour): argument is not numeric or logical: returning NA

#> Warning in mean.default(hour): argument is not numeric or logical: returning NA
#> Warning in mean.default(hour): argument is not numeric or logical: returning NA

#> Warning in mean.default(hour): argument is not numeric or logical: returning NA

return_data <- df_test %>%
  dplyr::mutate(
    hour = paste(hour, ':00'),
    across(.cols = c(x, y), scales::label_dollar())
  )
#> Error: Problem with `mutate()` input `..2`.
#> x subscript out of bounds
#> ? Input `..2` is `(function (.cols = everything(), .fns = NULL, ..., .names = NULL) ...`.

return_data <- df_test %>%
  dplyr::mutate(
    across(.cols = c(x, y), scales::label_dollar())
  )

return_data <- df_test %>%
  dplyr::mutate(
    hour = paste(hour, ':00'),
    across(.cols = c(x, y), scales::label_dollar())
  )
```

<sup>Created on 2021-03-06 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> - Session info ---------------------------------------------------------------
#>  setting  value                       
#>  version  R version 4.0.4 (2021-02-15)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  English_United States.1252  
#>  ctype    English_United States.1252  
#>  tz       America/Denver              
#>  date     2021-03-06                  
#> 
#> - Packages -------------------------------------------------------------------
#>  package     * version date       lib source           
#>  assertthat    0.2.1   2019-03-21 [1] CRAN (R 4.0.3)   
#>  cli           2.3.0   2021-01-31 [1] CRAN (R 4.0.3)   
#>  colorspace    2.0-0   2020-11-11 [1] CRAN (R 4.0.3)   
#>  crayon        1.4.1   2021-02-08 [1] CRAN (R 4.0.4)   
#>  DBI           1.1.1   2021-01-15 [1] CRAN (R 4.0.3)   
#>  digest        0.6.27  2020-10-24 [1] CRAN (R 4.0.3)   
#>  dplyr       * 1.0.5   2021-03-05 [1] standard (@1.0.5)
#>  ellipsis      0.3.1   2020-05-15 [1] CRAN (R 4.0.3)   
#>  evaluate      0.14    2019-05-28 [1] CRAN (R 4.0.3)   
#>  fs            1.5.0   2020-07-31 [1] CRAN (R 4.0.3)   
#>  generics      0.1.0   2020-10-31 [1] CRAN (R 4.0.3)   
#>  glue          1.4.2   2020-08-27 [1] CRAN (R 4.0.3)   
#>  highr         0.8     2019-03-20 [1] CRAN (R 4.0.3)   
#>  hms           1.0.0   2021-01-13 [1] CRAN (R 4.0.3)   
#>  htmltools     0.5.1.1 2021-01-22 [1] CRAN (R 4.0.3)   
#>  knitr         1.31    2021-01-27 [1] CRAN (R 4.0.3)   
#>  lifecycle     1.0.0   2021-02-15 [1] CRAN (R 4.0.4)   
#>  magrittr      2.0.1   2020-11-17 [1] CRAN (R 4.0.3)   
#>  munsell       0.5.0   2018-06-12 [1] CRAN (R 4.0.3)   
#>  pillar        1.4.7   2020-11-20 [1] CRAN (R 4.0.3)   
#>  pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.0.3)   
#>  ps            1.5.0   2020-12-05 [1] CRAN (R 4.0.3)   
#>  purrr         0.3.4   2020-04-17 [1] CRAN (R 4.0.3)   
#>  R6            2.5.0   2020-10-28 [1] CRAN (R 4.0.3)   
#>  readr       * 1.4.0   2020-10-05 [1] CRAN (R 4.0.3)   
#>  reprex        1.0.0   2021-01-27 [1] CRAN (R 4.0.3)   
#>  rlang         0.4.10  2020-12-30 [1] CRAN (R 4.0.3)   
#>  rmarkdown     2.6     2020-12-14 [1] CRAN (R 4.0.3)   
#>  rstudioapi    0.13    2020-11-12 [1] CRAN (R 4.0.3)   
#>  scales      * 1.1.1   2020-05-11 [1] CRAN (R 4.0.3)   
#>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 4.0.3)   
#>  stringi       1.5.3   2020-09-09 [1] CRAN (R 4.0.3)   
#>  stringr       1.4.0   2019-02-10 [1] CRAN (R 4.0.3)   
#>  tibble      * 3.0.6   2021-01-29 [1] CRAN (R 4.0.3)   
#>  tidyselect    1.1.0   2020-05-11 [1] CRAN (R 4.0.3)   
#>  vctrs         0.3.6   2020-12-17 [1] CRAN (R 4.0.3)   
#>  withr         2.4.1   2021-01-26 [1] CRAN (R 4.0.3)   
#>  xfun          0.20    2021-01-06 [1] CRAN (R 4.0.3)   
#>  yaml          2.2.1   2020-02-01 [1] CRAN (R 4.0.3)   
#> 
#> [1] C:/Users/ayip/Documents/R/R-4.0.4/library
```

</details>
